# Generated by Django 3.0.4 on 2020-06-03 15:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='opinions_file',
        ),
        migrations.AddField(
            model_name='product',
            name='opinions_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
