# Generated by Django 3.0.4 on 2020-06-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200603_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOpinion',
        ),
    ]
