# Generated by Django 3.0.4 on 2020-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20200603_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pie',
            field=models.ImageField(upload_to=''),
        ),
    ]
