# Generated by Django 3.0.4 on 2020-06-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20200604_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.TextField(default=''),
        ),
    ]
